{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "datadog.name" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "datadog.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreName }}
    kind: SecretStore
  target:
    name: {{ .Values.externalSecret.targetSecretName }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.datadogAgent.credentials.apiSecretKey }}
      remoteRef:
        key: {{ required "externalSecret.remoteRef.key is required" .Values.externalSecret.remoteRef.key }}
        property: {{ .Values.externalSecret.remoteRef.property }}
{{- end }}
