{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "custody.name" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "custody.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | default "30s" }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreName }}
    kind: SecretStore
  target:
    name: {{ .Values.externalSecret.targetSecretName }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.global.esoSecretName }}
{{- end }}
{{- $root := . }}
{{- range $item := .Values.additionalExternalSecrets }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $item.name }}
  namespace: {{ $root.Release.Namespace }}
  labels:
    {{- include "custody.labels" $root | nindent 4 }}
spec:
  refreshInterval: {{ $item.refreshInterval | default $root.Values.externalSecret.refreshInterval | default "30s" }}
  secretStoreRef:
    name: {{ $item.secretStoreName | default $root.Values.externalSecret.secretStoreName }}
    kind: SecretStore
  target:
    name: {{ $item.targetSecretName }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ $item.awsSecretName }}
{{- end }}
