{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "custody.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "custody.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "custody.selectorLabels" . | nindent 6 }}
  endpoints:
    - path: {{ .Values.monitoring.metricsPath }}
      interval: {{ .Values.monitoring.scrapeInterval }}
      scheme: http
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
