{{- range $name, $svc := .Values.services }}
{{- if and $svc.enabled $svc.service $svc.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "custody.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
  {{- with $svc.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $svc.service.type | default "ClusterIP" }}
  ports:
    - port: {{ $svc.service.port | default 80 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "custody.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
{{- end }}
{{- end }}
