{{- if .Values.secretStore.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.secretStore.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "exchange.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.global.awsRegion }}
      {{- if .Values.global.esoRoleArn }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ include "exchange.serviceAccountName" . }}
      {{- end }}
{{- end }}
